FROM mcr.microsoft.com/dotnet/runtime:%IMAGE_VERSION% AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:%IMAGE_VERSION% AS build
WORKDIR /src
COPY ["%REPO_DIR%/%REPO_DIR%.csproj", "%REPO_DIR%/"]
RUN dotnet restore "%REPO_DIR%/%REPO_DIR%.csproj"
COPY . .
WORKDIR "/src/%REPO_DIR%"
RUN dotnet build "%REPO_DIR%.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "%REPO_DIR%.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "%REPO_DIR%.dll"]